genisys-web/src/main/java/py/com/sepsa/genisys/web/controllers/usuarios/ListaMB.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package py.com.sepsa.genisys.web.controllers.usuarios;

import fa.gs.criteria.query.Order;
import fa.gs.misc.Assertions;
import fa.gs.utils.collections.Lists;
import fa.gs.utils.database.query.expressions.literals.SQLStringLiterals;
import fa.gs.utils.misc.text.Strings;
import java.io.Serializable;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.enterprise.context.Dependent;
import lombok.Data;
import py.com.sepsa.genisys.ejb.logic.impl.Usuarios;
import py.com.sepsa.genisys.ejb.logic.pojos.UsuarioInfo;
import py.com.sepsa.genisys.ejb.utils.Injection;
import py.com.sepsa.genisys.web.utils.CustomFilter;
import py.com.sepsa.genisys.web.utils.CustomLazyDataModel;

/**
 *
 * @author Néstor E. Reinoso Wood
 */
@Dependent
public class ListaMB extends py.com.sepsa.genisys.web.controllers.ListaMB<UsuarioInfo> implements Serializable {

    @Override
    protected CustomLazyDataModel<UsuarioInfo> buildItemsLoader() {
        if (usuarioLogueado.esAdministrador()) {
            return new UsuariosLazyList();
        } else {
            return new UsuariosDefaultLazyList();
        }
    }

    @Override
    protected CustomFilter buildItemsFilter() {
        return new UsuarioListFilter();
    }

    /**
     * Clase que encapsula la carga progresiva de facturas desde la BD.
     */
    private class UsuariosDefaultLazyList extends CustomLazyDataModel<UsuarioInfo> {

        /**
         * Constructor.
         */
        public UsuariosDefaultLazyList() {
            super(null);
        }

        /**
         * Realiza una carga lazy de datos desde la BD.
         *
         * @param offset cantidad de registros a omitor.
         * @param limit cantidad máxima de registros a obtener.
         * @param sorts criterios de ordenacion de datos.
         * @param filter criterios de filtrado de datos.
         * @return Lista de entidades recuperadas desde BD.
         */
        @Override
        public List<UsuarioInfo> lazyLoad(int offset, int limit, Map<String, Order> sorts, Map<String, Object> filter) {
            return Lists.empty();
        }

    }

    /**
     * Clase que encapsula la carga progresiva de facturas a mostrar a los
     * compradores.
     */
    private class UsuariosLazyList extends CustomLazyDataModel<UsuarioInfo> {

        private final Usuarios usuarios;

        /**
         * Constructor.
         */
        public UsuariosLazyList() {
            super(null);
            this.usuarios = Injection.lookup(Usuarios.class);
        }

        /**
         * Realiza una carga lazy de datos desde la BD.
         *
         * @param offset cantidad de registros a omitor.
         * @param limit cantidad máxima de registros a obtener.
         * @param sorts criterios de ordenacion de datos.
         * @param filter criterios de filtrado de datos.
         * @return Lista de entidades recuperadas desde BD.
         */
        @Override
        public List<UsuarioInfo> lazyLoad(int offset, int limit, Map<String, Order> sorts, Map<String, Object> filter) {
            // Ordenacion automatica.
            sorts.put("u.usuario", Order.ASCENDING);

            // Busqueda de registros.
            List<UsuarioInfo> data = usuarios.selectUsuarios(limit, offset, filter, sorts);
            Integer total = usuarios.countUsuarios(filter);
            setRowCount(total);
            return data;
        }

    }

    /**
     * Clase que encapsula los campos y operadores de filtro aplicables a la
     * lista principal de facturas.
     */
    @Data
    public class UsuarioListFilter extends CustomFilter {

        private Integer id;
        private String usuario;
        private String cliente;
        private String ruc;

        @Override
        final public void clearFilterValues() {
            this.id = null;
            this.usuario = "";
            this.cliente = "";
            this.ruc = "";
        }

        @Override
        public Map<String, Object> getFilters() {
            Map<String, Object> filters = new HashMap<>();

            // Filtro de id.
            if (!Assertions.isNull(id)) {
                filters.put("id", Strings.format(" u.id = %s ", id));
            }

            // Filtro de usuario.
            if (!Assertions.stringNullOrEmpty(usuario)) {
                filters.put("usuario", Strings.format(" u.usuario ilike '%s' ", SQLStringLiterals.likefy(usuario)));
            }

            // Filtro de cliente.
            if (!Assertions.stringNullOrEmpty(cliente)) {
                String a = SQLStringLiterals.likefy(cliente);
                filters.put("cliente", Strings.format(" (t0.razon_social ilike '%s' or t0.nombre_fantasia ilike '%s') ", a, a));
            }

            // Filtro de ruc.
            if (!Assertions.stringNullOrEmpty(ruc)) {
                String a = SQLStringLiterals.likefy(ruc);
                filters.put("cliente", Strings.format(" t0.ruc ilike '%s' ", a));
            }

            return filters;
        }

    }
}

genisys-web/src/main/java/py/com/sepsa/genisys/web/controllers/usuarios/UsuarioAltaMB.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package py.com.sepsa.genisys.web.controllers.usuarios;

import fa.gs.misc.Assertions;
import fa.gs.result.simple.Result;
import fa.gs.utils.collections.Lists;
import fa.gs.utils.collections.Sets;
import java.io.Serializable;
import java.util.Collection;
import java.util.List;
import java.util.Set;
import javax.annotation.PostConstruct;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.validation.ValidationException;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;
import py.com.generica.epos.web.utils.TxWrapperWeb;
import py.com.sepsa.genisys.ejb.entities.info.Persona;
import py.com.sepsa.genisys.ejb.logic.impl.Personas;
import py.com.sepsa.genisys.ejb.logic.impl.Sesiones;
import py.com.sepsa.genisys.ejb.logic.impl.Usuarios;
import py.com.sepsa.genisys.web.controllers.BasicViewMB;
import py.com.sepsa.genisys.web.utils.Prime;

/**
 *
 * @author Fabio A. González Sosa
 */
@Named(value = "usuarioAlta")
@ViewScoped
public class UsuarioAltaMB extends BasicViewMB implements Serializable {

    @Inject
    private Personas personas;

    @Inject
    private Sesiones sesiones;

    @Inject
    private Usuarios usuarios;

    @Inject
    private TxWrapperWeb tx;

    @Getter
    private Collection<Persona> personasSeleccionables;

    @Getter
    @Setter
    private FormInput input;

    @PostConstruct
    public void init() {
        // Inicializar conjunto de personas seleccionables.
        personasSeleccionables = initPersonasSeleccionables();

        // Inicializar formulario.
        input = new FormInput();
        input.persona = null;
        input.usuario = null;
        input.contrasena = null;
    }

    private Collection<Persona> initPersonasSeleccionables() {
        Set<Persona> personas0 = Sets.empty();
        personas0.addAll(this.personas.obtenerCompradoresDisponibles().value(Lists.empty()));
        personas0.addAll(this.personas.obtenerProveedoresDisponibles().value(Lists.empty()));
        personas0.addAll(this.personas.obtenerEntidadesFinancierasDisponibles().value(Lists.empty()));

        List<Persona> personas1 = Lists.empty();
        personas1.addAll(personas0);
        personas1.sort((Persona o1, Persona o2) -> o1.getRazonSocial().compareTo(o2.getRazonSocial()));
        return personas1;
    }

    public void guardar() {
        Result<Void> result = tx.execute(this::guardar0);
        if (result.isFailure()) {
            // Error.
            String msg = result.failure().cause().getMessage();
            mensajes.showGlobalDialogMessage(msg);
        } else {
            mensajes.showGlobalDialogMessage(() -> Prime.redirect("/app/abm/usuarios/lista.xhtml"), "Datos guardados exitosamente");
        }

        updateForm();
    }

    private Void guardar0() throws Throwable {
        // Validar datos de entrada.
        String err = validarInput(input);
        if (err != null) {
            throw new ValidationException(err);
        }

        // Registrar nuevo.
        usuarios.registrarNuevo(input.persona.getId(), input.usuario, input.contrasena);
        return null;
    }

    private String validarInput(FormInput input) {
        if (input.persona == null) {
            return "Se debe especificar un cliente";
        }

        if (Assertions.stringNullOrEmpty(input.usuario)) {
            return "Se debe especificar un nombre de usuario";
        }

        if (Assertions.stringNullOrEmpty(input.contrasena)) {
            return "Se debe especificar una contraseña";
        }

        Collection<?> existentes = sesiones.obtenerPorTransUsuario(input.usuario).value(Lists.empty());
        if (!Assertions.isNullOrEmpty(existentes)) {
            return "Se debe especificar un nombre de usuario que no exista previamente";
        }

        return null;
    }

    private void updateForm() {
        Prime.update("alta_usuario_form");
    }

    @Data
    public static class FormInput implements Serializable {

        private Persona persona;
        private String usuario;
        private String contrasena;
    }

}

genisys-web/src/main/java/py/com/sepsa/genisys/web/controllers/usuarios/UsuariosMB.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package py.com.sepsa.genisys.web.controllers.usuarios;

import fa.gs.misc.Assertions;
import fa.gs.utils.misc.text.Joiner;
import fa.gs.utils.misc.text.Strings;
import java.io.Serializable;
import javax.annotation.PostConstruct;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import lombok.Getter;
import lombok.Setter;
import org.omnifaces.util.Ajax;
import py.com.sepsa.genisys.ejb.enums.PerfilEnum;
import py.com.sepsa.genisys.ejb.logic.impl.Usuarios;
import py.com.sepsa.genisys.ejb.logic.pojos.UsuarioInfo;
import py.com.sepsa.genisys.ejb.utils.Ids;
import py.com.sepsa.genisys.ejb.utils.Text;
import py.com.sepsa.genisys.web.controllers.BasicViewMB;
import py.com.sepsa.genisys.web.utils.CustomFilter;
import py.com.sepsa.genisys.web.utils.Prime;

/**
 *
 * @author Néstor E. Reinoso Wood
 */
@Named(value = "usuarios")
@ViewScoped
public class UsuariosMB extends BasicViewMB implements Serializable {

    @Inject
    private Usuarios usuarios;

    @Inject
    @Getter
    @Setter
    private py.com.sepsa.genisys.web.controllers.usuarios.ListaMB lista;

    @PostConstruct
    public void init() {
        ;
    }

    public void initAltaUsuario() {
        Prime.redirect("app/abm/usuarios/alta.xhtml?redirect-true");
    }

    public void eliminarUsuario() {
        UsuarioInfo item = checkSeleccionUnica(lista);
        if (item != null) {
            try {
                usuarios.inhabilitar(item.getId());
                mensajes.showGlobalDialogMessage("Usuario eliminado exitosamente");
                updateViewListaDeUsuarios();
            } catch (Throwable thr) {
                mensajes.showGlobalDialogMessage("Ocurrió un error eliminando usuario");
            }
        }
    }

    public void initHabilitarPerfil() {
        UsuarioInfo item = checkSeleccionUnica(lista);
        if (item != null) {
            String id = Ids.mask(item.getId());
            String path = Strings.format("app/abm/usuarios/habilitar_perfil.xhtml?u=%s", id);
            Prime.redirect(path);
        }
    }

    public void initCambiarContrasena() {
        UsuarioInfo item = checkSeleccionUnica(lista);
        if (item != null) {
            String id = Ids.mask(item.getId());
            String path = Strings.format("app/abm/usuarios/cambiar_pass.xhtml?u=%s", id);
            Prime.redirect(path);
        }
    }

    public String razonSocial(UsuarioInfo item) {
        if (Assertions.stringNullOrEmpty(item.getRazonSocial())) {
            return Text.nd();
        } else {
            return item.getRazonSocial().trim();
        }
    }

    public String nombreFantasia(UsuarioInfo item) {
        if (Assertions.stringNullOrEmpty(item.getNombreFantasia())) {
            return Text.nd();
        } else {
            return item.getNombreFantasia().trim();
        }
    }

    public String ruc(UsuarioInfo item) {
        String ruc = Joiner.of(item.getRuc(), item.getDvRuc()).separator("-").join().trim();
        if (ruc.endsWith("-")) {
            ruc = ruc.substring(0, ruc.length() - 1);
        }
        return ruc;
    }

    public String perfiles(UsuarioInfo item) {
        String[] parts = item.getIdPerfilAgg().split(";");
        if (parts.length == 0) {
            return Text.nd();
        } else if (parts.length == 1) {
            return PerfilEnum.descripcionAsSimpleText(parts[0]);
        } else {
            return Joiner.of(parts)
                    .adapter(e -> Strings.format("<div>&bull;&nbsp;%s</div>", PerfilEnum.descripcionAsSimpleText(e)))
                    .separator(" ")
                    .join();
        }
    }

    public void filtrarLista() {
        lista.filter();
        updateViewFiltrosForm();
    }

    public void limpiarFiltroForm() {
        CustomFilter filtro = lista.getFiltro();
        if (!filtro.isEnabled()) {
            filtro.clearFilterValues();
            updateViewFiltrosForm();
        }
    }

    public void recargarListaUsuarios() {
        lista.clearSelections();
        updateViewListaDeUsuarios();
        lista.reload();
        updateViewListaDeUsuarios();
    }

    private void updateViewFiltrosForm() {
        Ajax.update("filtro_usuarios_panel:filtro_usuarios_form");
        Prime.showBlockUi("bui", lista.getFiltro().isEnabled());
        updateViewListaDeUsuarios();
    }

    private void updateViewListaDeUsuarios() {
        lista.clearSelections();
        Ajax.update("tabla_usuarios_panel:tabla_usuarios_form:tabla_usuarios");
        Prime.executeJs("$.fn.matchHeight._update();");
    }

    //<editor-fold defaultstate="collapsed" desc="Getters y Setters">
    public String getBtnFiltrarText() {
        if (lista.getFiltro().isEnabled()) {
            return "Deshacer Filtro";
        } else {
            return "Filtrar Datos";
        }
    }

    public String getOpcionesPanelClass() {
        if (!usuarioLogueado.esAdministrador()) {
            return "hidden";
        } else {
            return "col-md-2";
        }
    }

    public String getListaUsuariosPanelClass() {
        if (!usuarioLogueado.esAdministrador()) {
            return "col-md-12";
        } else {
            return "col-md-10";
        }
    }
    //</editor-fold>

}

genisys-web/src/main/webapp/app/abm/usuarios/alta.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:sepsa="http://java.sun.com/jsf/composite/components"
      xmlns:sec="http://www.springframework.org/security/tags"
      >

    <ui:composition template="../../../templates/template.xhtml">
        <ui:define name="content">
            <sec:authorize access="hasRole('ROLE_ADMINISTRADOR')">
                <div class="container well" style="background: white;">
                    <ui:include src="/app/abm/usuarios/fragments/usuario_nuevo.xhtml" />
                </div>
            </sec:authorize>
        </ui:define>
    </ui:composition>
</html>

genisys-web/src/main/webapp/app/abm/usuarios/cambiar_pass.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:sepsa="http://java.sun.com/jsf/composite/components"
      xmlns:sec="http://www.springframework.org/security/tags"
      >

    <ui:composition template="../../../templates/template.xhtml">
        <ui:define name="content">
            <sec:authorize access="hasRole('ROLE_ADMINISTRADOR')">
                <div class="container well" style="background: white;">
                    <ui:include src="/app/abm/usuarios/fragments/cambiar_pass.xhtml" />
                </div>
            </sec:authorize>
        </ui:define>
    </ui:composition>
</html>

genisys-web/src/main/webapp/app/abm/usuarios/habilitar_perfil.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:sepsa="http://java.sun.com/jsf/composite/components"
      xmlns:sec="http://www.springframework.org/security/tags"
      >

    <ui:composition template="../../../templates/template.xhtml">
        <ui:define name="content">
            <sec:authorize access="hasRole('ROLE_ADMINISTRADOR')">
                <div class="container well" style="background: white;">
                    <ui:include src="/app/abm/usuarios/fragments/habilitar_perfil.xhtml" />
                </div>
            </sec:authorize>
        </ui:define>
    </ui:composition>
</html>

genisys-web/src/main/webapp/app/abm/usuarios/lista.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:sepsa="http://java.sun.com/jsf/composite/components"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:sec="http://www.springframework.org/security/tags"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <ui:composition template="../../../templates/template.xhtml">
        <ui:define name="content">
            <!-- FILTROS PARA LISTA DE USUARIOS -->
            <div class="row">
                <div class="col-md-12">
                    <sepsa:panel id="filtro_usuarios_panel">
                        <f:facet name="panelHeader">
                            Filtros de Búsqueda
                        </f:facet>
                        <f:facet name="panelBody">
                            <ui:include src="/app/abm/usuarios/fragments/tabla_filtros.xhtml" />
                        </f:facet>
                    </sepsa:panel>
                </div>
            </div>

            <div class="row">
                <!-- MENU DE OPCIONES -->
                <div class="#{usuarios.opcionesPanelClass}">
                    <sec:authorize access="hasRole('ROLE_ADMINISTRADOR')" >
                        <h:form>
                            <input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}"/>
                            <sepsa:panel  inlineBody="true" panelId="t">
                                <f:facet name="panelHeader">
                                    Opciones
                                </f:facet>
                                <f:facet name="panelBody">
                                    <div class="list-group">
                                        <div class="list-group-item app_no_border">
                                            <p:commandButton class="btn-block" value="Nuevo" icon="fa fa-check" action="#{usuarios.initAltaUsuario}" />
                                        </div>
                                        <div class="list-group-item app_no_border">
                                            <p:commandButton class="btn-block" value="Eliminar" icon="fa fa-trash" action="#{usuarios.eliminarUsuario}" />
                                        </div>
                                        <div class="list-group-item app_no_border">
                                            <p:commandButton class="btn-block" value="Habilitar Perfil" action="#{usuarios.initHabilitarPerfil}" />
                                        </div>
                                        <div class="list-group-item app_no_border">
                                            <p:commandButton class="btn-block" value="Cambiar Contraseña" action="#{usuarios.initCambiarContrasena}" />
                                        </div>
                                    </div>
                                </f:facet>
                            </sepsa:panel>
                        </h:form>
                    </sec:authorize>
                </div>

                <!-- LISTA DE USUARIOS -->
                <div class="#{usuarios.listaUsuariosPanelClass}">
                    <sepsa:panel id="tabla_usuarios_panel" panelId="s">
                        <f:facet name="panelHeader">
                            <h4 class="app_panel_title pull-left">Lista de Usuarios</h4>
                            <div class="btn-group pull-right">
                                <h:form>
                                    <input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}"/>
                                    <p:commandLink class="btn btn-default btn-sm" action="#{usuarios.recargarListaUsuarios}"><i class="fa fa-refresh"/></p:commandLink>
                                </h:form>
                            </div>
                        </f:facet>
                        <f:facet name="panelBody">
                            <ui:include src="/app/abm/usuarios/fragments/tabla_usuarios.xhtml" />
                        </f:facet>
                    </sepsa:panel>
                </div>
            </div>

            <script type="application/javascript">
                $(document).ready(function() {
                var s = $('[data-panel-id="s"]')[0];
                var t = $('[data-panel-id="t"]')[0];
                addStickyOperacionesBehavior(s, t);
                });
            </script>
        </ui:define>
    </ui:composition>
</html>