genisys-web/src/main/java/py/com/sepsa/genisys/web/controllers/entidades/AdhesionCompradorMB.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package py.com.sepsa.genisys.web.controllers.entidades;

import fa.gs.result.simple.Result;
import fa.gs.result.simple.Results;
import fa.gs.utils.collections.Lists;
import fa.gs.utils.misc.Todo;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Collection;
import java.util.Date;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.event.AjaxBehaviorEvent;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;
import py.com.generica.epos.web.utils.TxWrapperWeb;
import py.com.sepsa.genisys.ejb.entities.factoring.BancoRioActividadEconomica;
import py.com.sepsa.genisys.ejb.entities.factoring.BancoRioCiudad;
import py.com.sepsa.genisys.ejb.entities.factoring.BancoRioRegion;
import py.com.sepsa.genisys.ejb.entities.factoring.BancoRioTipoSociedad;
import py.com.sepsa.genisys.ejb.entities.info.Persona;
import py.com.sepsa.genisys.ejb.logic.impl.BancoRio;
import py.com.sepsa.genisys.integraciones.banco_rio.RegistroCompradorPersonaJuridicaInput;
import py.com.sepsa.genisys.integraciones.banco_rio.RegistroCompradorPersonaJuridicaOutput;
import py.com.sepsa.genisys.integraciones.banco_rio.pojos.ContactoInfo;
import py.com.sepsa.genisys.integraciones.banco_rio.pojos.DireccionInfo;
import py.com.sepsa.genisys.integraciones.banco_rio.pojos.DocumentoInfo;
import py.com.sepsa.genisys.integraciones.banco_rio.pojos.RubroInfo;
import py.com.sepsa.genisys.integraciones.banco_rio.pojos.SociedadInfo;
import py.com.sepsa.genisys.web.controllers.BasicViewMB;
import py.com.sepsa.genisys.web.controllers.varios.PersonasMB;
import py.com.sepsa.genisys.web.utils.Html;

/**
 *
 * @author Fabio A. González Sosa
 */
@Named(value = "adhesionEntidadComprador")
@ViewScoped
public class AdhesionCompradorMB extends BasicViewMB implements Serializable {

    @Inject
    private PersonasMB personas;

    @Inject
    private TxWrapperWeb tx;

    @Getter
    @Setter
    private Persona entidadSelected;

    //<editor-fold defaultstate="collapsed" desc="Banco Rio">
    @EJB
    private BancoRio integracionBancoRio;

    @Getter
    @Setter
    private FormInputBancoRio formBancoRio;

    @Getter
    @Setter
    private Collection<BancoRioTipoSociedad> bancoRioTiposSociedad;

    @Getter
    @Setter
    private Collection<BancoRioActividadEconomica> bancoRioActividadesEconomicas;

    @Getter
    @Setter
    private Collection<BancoRioCiudad> bancoRioCiudades;
    //</editor-fold>

    @PostConstruct
    public void init() {
        // Inicializar entidad financiera.
        this.entidadSelected = null;
    }

    public boolean entidadEstaSeleccionada() {
        return entidadSelected != null;
    }

    public boolean entidadSeleccionadaEsBancoRio() {
        if (entidadEstaSeleccionada()) {
            return integracionBancoRio.esBancoRio(entidadSelected.getId());
        } else {
            return false;
        }
    }

    public Collection<Persona> getEntidadesSeleccionables() {
        return personas.getEntidadesFinancieras();
    }

    public void onEntidadSelectedChanged(AjaxBehaviorEvent event) {
        try {
            if (entidadSelected != null) {
                // Validar si existen relaciones anteriores.
                Todo.TODO();

                // Verificar tipo de banco.
                if (entidadSeleccionadaEsBancoRio()) {
                    onEntidadSelectedEsBancoRio();
                }
            } else {
                mensajes.addMessageWarning("Advertencia", "Se debe seleccionar una entidad financiera.");
            }
        } catch (Throwable thr) {
            // Error.
            entidadSelected = null;
            log.warning(thr, "Ocurrió un error seleccionando entidad financiera para adhesion.");
            mensajes.addMessageError("Error", "Ocurrió un error seleccionando entidad financiera para adhesion.");
        }
    }

    //<editor-fold defaultstate="collapsed" desc="Adhesion - Banco Rio">
    private void onEntidadSelectedEsBancoRio() {
        // Inicializar contenedor de datos de entrada.
        this.formBancoRio = new FormInputBancoRio();

        // Inicializar datos seleccionables.
        this.bancoRioTiposSociedad = bancoRioTipoSociedadesSeleccionables();
        this.bancoRioActividadesEconomicas = bancoRioActividadesEconomicasSeleccionables();
        this.bancoRioCiudades = bancoRioCiudadesSeleccionables();
    }

    private Collection<BancoRioActividadEconomica> bancoRioActividadesEconomicasSeleccionables() {
        Result<Collection<BancoRioActividadEconomica>> result = integracionBancoRio.obtenerActividadesEconomicas();
        if (result.isFailure()) {
            log.error(result.failure().cause(), result.failure().message());
        }
        return result.value(Lists.empty());
    }

    public String bancoRioActividadEconomicaLabel(BancoRioActividadEconomica item) {
        if (item == null) {
            return Html.selectItemEmpty();
        } else {
            return Html.selectItem(item.getDescripcion(), item.getCodigo());
        }
    }

    private Collection<BancoRioTipoSociedad> bancoRioTipoSociedadesSeleccionables() {
        Result<Collection<BancoRioTipoSociedad>> result = integracionBancoRio.obtenerTiposSociedades();
        if (result.isFailure()) {
            log.error(result.failure().cause(), result.failure().message());
        }
        return result.value(Lists.empty());
    }

    public String bancoRioTipoSociedadLabel(BancoRioTipoSociedad item) {
        if (item == null) {
            return Html.selectItemEmpty();
        } else {
            return Html.selectItem(item.getDescripcion(), item.getSigla());
        }
    }

    private Collection<BancoRioCiudad> bancoRioCiudadesSeleccionables() {
        Result<Collection<BancoRioCiudad>> result = integracionBancoRio.obtenerCiudades();
        if (result.isFailure()) {
            log.error(result.failure().cause(), result.failure().message());
        }
        return result.value(Lists.empty());
    }

    public String bancoRioCiudadLabel(BancoRioCiudad item) {
        if (item == null) {
            return Html.selectItemEmpty();
        } else {
            return Html.selectItem(item.getDescripcion(), item.getCodigo());
        }
    }

    public void onBancoRioCiudadSelected(AjaxBehaviorEvent event) {
        try {
            // Validar relaciones anteriores.
            if (formBancoRio.ciudad != null) {
                // Obtener region correspondiente.
                Result<BancoRioRegion> resRegion = integracionBancoRio.obtenerRegionPorCodigo(formBancoRio.ciudad.getCodigoRegion());
                resRegion.raise();
                formBancoRio.region = resRegion.value();
            } else {
                formBancoRio.region = null;
            }
        } catch (Throwable thr) {
            // Error.
            entidadSelected = null;
            log.warning(thr, "Ocurrió un error seleccionando ciudad.");
            mensajes.addMessageError("Error", "Ocurrió un error seleccionando ciudad.");
        }
    }

    public Collection<BancoRioRegion> bancoRioRegionesSeleccionables() {
        Result<Collection<BancoRioRegion>> result = integracionBancoRio.obtenerRegiones();
        if (result.isFailure()) {
            log.error(result.failure().cause(), result.failure().message());
        }
        return result.value(Lists.empty());
    }

    public String bancoRioRegionLabel(BancoRioRegion item) {
        if (item == null) {
            return Html.selectItemEmpty();
        } else {
            return Html.selectItem(item.getDescripcion(), item.getCodigo());
        }
    }

    private Void bancoRioOnConfirmar() throws Throwable {
        Integer idPersona = usuarioLogueado.getPersona().getId();
        Integer idPerfil = usuarioLogueado.getPerfil().getId();
        Integer idEntidadFinanciera = entidadSelected.getId();

        // Registro de persona fisica.
        if (usuarioLogueado.esPersonaFisica()) {
            // TODO: IMPLEMENTAR.
        }

        // Registro de persona juridica.
        if (usuarioLogueado.esPersonaJuridica()) {
            RegistroCompradorPersonaJuridicaInput input = adaptRegistroCompradorPersonaInput();
            Result<RegistroCompradorPersonaJuridicaOutput> result = integracionBancoRio.registrarComprador(idPersona, idPerfil, idEntidadFinanciera, input);
            result.raise();
        }

        // Ok.
        return null;
    }

    private RegistroCompradorPersonaJuridicaInput adaptRegistroCompradorPersonaInput() {
        // Datos de proveedor.
        String razonSocial0 = usuarioLogueado.getPersona().getPjRazonSocial();

        // Datos de documento.
        DocumentoInfo documento0 = integracionBancoRio.resolveDocumento(usuarioLogueado.getPersona());

        // Datos de sociedad.
        SociedadInfo sociedad0 = new SociedadInfo();
        sociedad0.setTipoSociedad(formBancoRio.tipoSociedad);
        sociedad0.setFechaConstitucion(formBancoRio.fechaConstitucion);

        // Datos de direccion.
        DireccionInfo direccion0 = new DireccionInfo();
        direccion0.setCalle1(usuarioLogueado.getDireccion().getCalle1());
        direccion0.setCalle2(usuarioLogueado.getDireccion().getCalle2());
        direccion0.setReferencia("Y");
        direccion0.setNroCalle(usuarioLogueado.getDireccion().getNroCalle());
        direccion0.setCalle3(usuarioLogueado.getDireccion().getCalle3());
        direccion0.setBarrio(usuarioLogueado.getDireccion().getBarrio());
        direccion0.setCiudad(formBancoRio.ciudad);
        direccion0.setRegion(formBancoRio.region);

        // Datos de contacto.
        ContactoInfo contacto0 = new ContactoInfo();

genisys-web/src/main/java/py/com/sepsa/genisys/web/controllers/entidades/AdhesionProveedorMB.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package py.com.sepsa.genisys.web.controllers.entidades;

import fa.gs.result.simple.Result;
import fa.gs.result.simple.Results;
import fa.gs.utils.misc.text.Strings;
import java.io.Serializable;
import java.util.Collection;
import javax.annotation.PostConstruct;
import javax.faces.event.AjaxBehaviorEvent;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import lombok.Getter;
import lombok.Setter;
import py.com.generica.epos.web.utils.TxWrapperWeb;
import py.com.sepsa.genisys.ejb.entities.info.Persona;
import py.com.sepsa.genisys.ejb.logic.impl.Entidades;
import py.com.sepsa.genisys.web.controllers.BasicViewMB;
import py.com.sepsa.genisys.web.controllers.varios.PersonasMB;

/**
 *
 * @author Fabio A. González Sosa
 */
@Named(value = "adhesionEntidadProveedor")
@ViewScoped
public class AdhesionProveedorMB extends BasicViewMB implements Serializable {

    @Inject
    private PersonasMB personas;

    @Inject
    private Entidades entidades;

    @Inject
    private TxWrapperWeb tx;

    @Getter
    @Setter
    private Persona entidadSelected;

    @Inject
    @Getter
    @Setter
    private AdhesionProveedor_BancoRio adhesionProveedorBancoRio;

    @PostConstruct
    public void init() {
        // Inicializar entidad financiera.
        this.entidadSelected = null;
    }

    public boolean entidadEstaSeleccionada() {
        return entidadSelected != null;
    }

    public boolean entidadSeleccionadaEsBancoRio() {
        if (entidadEstaSeleccionada()) {
            return adhesionProveedorBancoRio.esBancoRio(entidadSelected.getId());
        } else {
            return false;
        }
    }

    public Collection<Persona> getEntidadesSeleccionables() {
        return personas.getEntidadesFinancieras();
    }

    public void onEntidadSelectedChanged(AjaxBehaviorEvent event) {
        try {
            if (entidadSelected != null) {
                // Validar si existen relaciones anteriores.
                Result<Entidades.EstadoAdhesionEntidad> resEstadoAdhesion = entidades.obtenerEstadoAdhesion(usuarioLogueado.getPersona().getId(), usuarioLogueado.getPerfil().getId(), entidadSelected.getId());
                if (resEstadoAdhesion.isFailure()) {
                    mensajes.addMessageError("Error", resEstadoAdhesion.failure().message());
                    entidadSelected = null;
                    return;
                }
                Entidades.EstadoAdhesionEntidad estado = resEstadoAdhesion.value();
                if (estado != null && estado != Entidades.EstadoAdhesionEntidad.RECHAZADO) {
                    mensajes.addMessageWarning("Advertencia", Strings.format("Ya existe una solicitud previa con estado %s para la entidad seleccionada", estado.toString()));
                    entidadSelected = null;
                    return;
                }

                // Iniciar nueva solicitud de adhesion.
                if (entidadSeleccionadaEsBancoRio()) {
                    adhesionProveedorBancoRio.onEntidadSelected();
                }
            } else {
                mensajes.addMessageWarning("Advertencia", "Se debe seleccionar una entidad financiera.");
            }
        } catch (Throwable thr) {
            // Error.
            entidadSelected = null;
            log.warning(thr, "Ocurrió un error seleccionando entidad financiera para adhesion.");
            mensajes.addMessageError("Error", "Ocurrió un error seleccionando entidad financiera para adhesion.");
        }
    }

    public void confirmar() {
        // Validar datos de entrada.
        String err = validarInput();
        if (err != null) {
            mensajes.addMessageError("Error", err);
            return;
        }

        // Confirmar datos.
        Result<?> result = onConfirmar();
        if (result.isFailure()) {
            log.error(result.failure().cause(), "Ocurrio un error confirmando adhesion a entidad financiera");
            mensajes.showGlobalDialogMessage(result.failure().cause().getMessage());
        } else {
            mensajes.showGlobalDialogMessage("Solicitud Registrada exitosamente");
            entidadSelected = null;
        }
    }

    private Result<Void> onConfirmar() {
        Result<Void> result;

        try {
            // Confirmar registro - Banco Rio.
            if (entidadSeleccionadaEsBancoRio()) {
                Result<Void> txResult = tx.execute(() -> adhesionProveedorBancoRio.onConfirmar(entidadSelected));
                if (txResult.isFailure()) {
                    throw txResult.failure().cause();
                }
            }

            result = Results.ok()
                    .nullable(true)
                    .build();
        } catch (Throwable thr) {
            result = Results.ko()
                    .cause(thr)
                    .build();
        }

        return result;
    }

    private String validarInput() {
        // Validacion: Banco Rio.
        if (entidadSeleccionadaEsBancoRio()) {
            return adhesionProveedorBancoRio.validarInput(entidadSelected);
        }

        return null;
    }

}

genisys-web/src/main/webapp/app/abm/entidades/fragments/adhesion_comprador.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:sec="http://www.springframework.org/security/tags"
    xmlns:p="http://primefaces.org/ui"
    xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
    xmlns:sepsa="http://java.sun.com/jsf/composite/components"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets">

    <h:form id="adhesion_form">
        <div class="form-group row">
            <div class="col-md-12">
                <div class="h3">Solicitud de Adhesión</div>
                <hr/>
            </div>
        </div>

        <div class="form-group row">
            <label class="form-control-label col-md-2">Entidad Financiera</label>
            <div class="col-md-4">
                <p:selectOneMenu value="#{adhesionEntidadComprador.entidadSelected}" class="app_form_input" converter="omnifaces.SelectItemsConverter" var="entidad" filter="true" filterMatchMode="contains">
                    <p:ajax listener="#{adhesionEntidadComprador.onEntidadSelectedChanged}" process="@form" update="@form" />
                    <f:selectItem itemValue="#{null}" itemLabel="" />
                    <f:selectItems value="#{adhesionEntidadComprador.entidadesSeleccionables}" />
                    <p:column>
                        <h:outputText value="#{utils.personaLabel(entidad)}" escape="false"/>
                    </p:column>
                </p:selectOneMenu>
            </div>
        </div>

        <!-- BANCO RIO -->
        <ui:fragment rendered="#{adhesionEntidadComprador.entidadSeleccionadaEsBancoRio()}">
            <ui:include src="/app/abm/entidades/fragments/adhesion_comprador_banco_rio.xhtml" />
        </ui:fragment>

        <h:panelGroup layout="block" class="form-group row" rendered="#{adhesionEntidadComprador.entidadEstaSeleccionada()}">
            <div class="col-md-12">
                <p:commandButton value="Confirmar" action="#{adhesionEntidadComprador.confirmar}" process="@form" update="@form" />
            </div>
        </h:panelGroup>

        <!-- MENSAJES DE ERROR -->
        <div class="form-group row">
            <div class="col-md-12">
                <sepsa:messages />
            </div>
        </div>
    </h:form>

</ui:composition>

genisys-web/src/main/webapp/app/abm/entidades/fragments/adhesion_comprador_banco_rio.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:sec="http://www.springframework.org/security/tags"
    xmlns:p="http://primefaces.org/ui"
    xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
    xmlns:sepsa="http://java.sun.com/jsf/composite/components"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets">

    <div class="form-group row">
        <div class="col-md-12">
            <div class="h3">Datos de Comprador</div>
            <hr/>
        </div>
    </div>

    <div class="form-group row">
        <label class="form-control-label col-md-2">Tipo</label>
        <div class="col-md-4">
            <p:inputText class="app_form_input" value="#{usuarioLogueado.htmlPersonaTipo()}" disabled="true" />
        </div>
    </div>

    <div class="form-group row">
        <label class="form-control-label col-md-2">Razón Social</label>
        <div class="col-md-4">
            <p:inputText class="app_form_input" value="#{usuarioLogueado.htmlPersonaRazonSocial()}" disabled="true" />
        </div>
    </div>

    <div class="form-group row">
        <label class="form-control-label col-md-2">RUC</label>
        <div class="col-md-4">
            <p:inputText class="app_form_input" value="#{usuarioLogueado.htmlPersonaRuc()}" disabled="true"/>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-md-12">
            <hr/>
        </div>
    </div>

    <div class="form-group row">
        <label class="form-control-label col-md-2">Actividad Económica</label>
        <div class="col-md-4">
            <p:selectOneMenu value="#{adhesionEntidadComprador.formBancoRio.actividadEconomica}" class="app_form_input" converter="omnifaces.SelectItemsConverter" var="item" filter="true" filterMatchMode="contains">
                <f:selectItem itemValue="#{null}" itemLabel="" />
                <f:selectItems value="#{adhesionEntidadComprador.bancoRioActividadesEconomicas}" />
                <p:column>
                    <h:outputText value="#{adhesionEntidadComprador.bancoRioActividadEconomicaLabel(item)}" escape="false"/>
                </p:column>
            </p:selectOneMenu>
        </div>
    </div>

    <div class="form-group row">
        <label class="form-control-label col-md-2">Tipo de Sociedad</label>
        <div class="col-md-4">
            <p:selectOneMenu value="#{adhesionEntidadComprador.formBancoRio.tipoSociedad}" class="app_form_input" converter="omnifaces.SelectItemsConverter" var="item" filter="true" filterMatchMode="contains">
                <f:selectItem itemValue="#{null}" itemLabel="" />
                <f:selectItems value="#{adhesionEntidadComprador.bancoRioTiposSociedad}" />
                <p:column>
                    <h:outputText value="#{adhesionEntidadComprador.bancoRioTipoSociedadLabel(item)}" escape="false"/>
                </p:column>
            </p:selectOneMenu>
        </div>
    </div>

    <div class="form-group row">
        <label class="form-control-label col-md-2">Fecha de Constitución</label>
        <div class="col-md-4">
            <p:calendar value="#{adhesionEntidadComprador.formBancoRio.fechaConstitucion}" class="app_text_uppercase app_form_input_addon_right" navigator="true" yearRange="c-100:c+100" pattern="dd/MMM/yyyy" mode="popup" locale="es" readonlyInput="true" />
        </div>
    </div>

    <div class="form-group row">
        <div class="col-md-2">
            <div class="form-control-label">Promedio de Facturación</div>
            <span class="form-text text-muted">Últimos 6 meses</span>
        </div>
        <div class="col-md-4">
            <p:inputText class="app_form_input" value="#{adhesionEntidadComprador.formBancoRio.facturacionPromedio}" onfocus="inputNumericOnFocus(this)">
                <p:ajax event="keyup" update="@this" global="false" delay="200" />
                <f:converter converterId="py.com.sepsa.genisys.web.utils.BigDecimalConverter" />
            </p:inputText>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-md-12">
            <hr/>
        </div>
    </div>

    <div class="form-group row">
        <label class="form-control-label col-md-2">Barrio</label>
        <div class="col-md-4">
            <p:inputText class="app_form_input" value="#{usuarioLogueado.htmlPersonaBarrio()}" disabled="true" />
        </div>
    </div>

    <div class="form-group row">
        <label class="form-control-label col-md-2">Ciudad</label>
        <div class="col-md-4">
            <p:selectOneMenu value="#{adhesionEntidadComprador.formBancoRio.ciudad}" class="app_form_input" converter="omnifaces.SelectItemsConverter" var="item" filter="true" filterMatchMode="contains">
                <p:ajax listener="#{adhesionEntidadComprador.onBancoRioCiudadSelected}" process="@form" update="@form" />
                <f:selectItem itemValue="#{null}" itemLabel="" />
                <f:selectItems value="#{adhesionEntidadComprador.bancoRioCiudades}" />
                <p:column>
                    <h:outputText value="#{adhesionEntidadComprador.bancoRioCiudadLabel(item)}" escape="false"/>
                </p:column>
            </p:selectOneMenu>
        </div>
    </div>

</ui:composition>

genisys-web/src/main/webapp/app/abm/entidades/fragments/adhesion_proveedor.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:sec="http://www.springframework.org/security/tags"
    xmlns:p="http://primefaces.org/ui"
    xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
    xmlns:sepsa="http://java.sun.com/jsf/composite/components"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets">

    <h:form id="adhesion_form">
        <div class="form-group row">
            <div class="col-md-12">
                <div class="h3">Solicitud de Adhesión</div>
                <hr/>
            </div>
        </div>

        <div class="form-group row">
            <label class="form-control-label col-md-2">Entidad Financiera</label>
            <div class="col-md-4">
                <p:selectOneMenu value="#{adhesionEntidadProveedor.entidadSelected}" class="app_form_input" converter="omnifaces.SelectItemsConverter" var="entidad" filter="true" filterMatchMode="contains">
                    <p:ajax listener="#{adhesionEntidadProveedor.onEntidadSelectedChanged}" process="@form" update="@form" />
                    <f:selectItem itemValue="#{null}" itemLabel="" />
                    <f:selectItems value="#{adhesionEntidadProveedor.entidadesSeleccionables}" />
                    <p:column>
                        <h:outputText value="#{utils.personaLabel(entidad)}" escape="false"/>
                    </p:column>
                </p:selectOneMenu>
            </div>
        </div>

        <!-- BANCO RIO -->
        <ui:fragment rendered="#{adhesionEntidadProveedor.entidadSeleccionadaEsBancoRio()}">
            <ui:include src="/app/abm/entidades/fragments/adhesion_proveedor_banco_rio.xhtml" />
        </ui:fragment>

        <h:panelGroup layout="block" class="form-group row" rendered="#{adhesionEntidadProveedor.entidadEstaSeleccionada()}">
            <div class="col-md-12">
                <p:commandButton value="Confirmar" action="#{adhesionEntidadProveedor.confirmar}" process="@form" update="@form" />
            </div>
        </h:panelGroup>

        <!-- MENSAJES DE ERROR -->
        <div class="form-group row">
            <div class="col-md-12">
                <sepsa:messages />
            </div>
        </div>
    </h:form>

</ui:composition>

genisys-web/src/main/webapp/app/abm/entidades/fragments/estado_solicitud_adhesion.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:sec="http://www.springframework.org/security/tags"
    xmlns:p="http://primefaces.org/ui"
    xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
    xmlns:sepsa="http://java.sun.com/jsf/composite/components"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets">

    <h:form id="estado_solicitud_adhesion_dialog_form">
        <h3>Estado de Solicitud de Adhesión</h3>
        <br/>
        <h:outputText value="#{entidades.htmlLastConsultaEstadoAdhesion}" escape="false" />
    </h:form>

</ui:composition>