genisys-web/src/main/java/py/com/sepsa/genisys/web/controllers/comprador/CompradorAltaMB.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package py.com.sepsa.genisys.web.controllers.comprador;

import fa.gs.result.simple.Result;
import fa.gs.utils.misc.Assertions;
import fa.gs.utils.misc.errors.Errors;
import java.io.Serializable;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.validation.ValidationException;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;
import py.com.generica.epos.web.utils.TxWrapperWeb;
import py.com.sepsa.genisys.ejb.entities.info.Persona;
import py.com.sepsa.genisys.ejb.entities.trans.PersonaRol;
import py.com.sepsa.genisys.ejb.enums.PerfilEnum;
import py.com.sepsa.genisys.ejb.logic.impl.Personas;
import py.com.sepsa.genisys.web.controllers.BasicViewMB;
import py.com.sepsa.genisys.web.utils.Prime;

/**
 *
 * @author Fabio A. González Sosa
 */
@Named(value = "altaComprador")
@ViewScoped
public class CompradorAltaMB extends BasicViewMB implements Serializable {

    @Inject
    private TxWrapperWeb tx;

    @Getter
    @Setter
    private CompradorAltaMB.Input input;

    @EJB
    private Personas personas;

    @PostConstruct
    public void init() {
        // Inicializar campos de entrada.
        initInput();
    }

    private void initInput() {
        this.input = new CompradorAltaMB.Input();
    }

    public void guardar() {
        Result<Void> result = tx.execute(this::guardar0);
        if (result.isFailure()) {
            // Error.
            String msg = result.failure().cause().getCause().getMessage();
            mensajes.showGlobalDialogMessage(msg);
        } else {
            // Limpiar campos de entrada.
            initInput();
            mensajes.showGlobalDialogMessage("Datos guardados exitosamente");
        }

        updateViewAltaFacturaForm();
    }

    private Void guardar0() throws Throwable {
        // Validar datos de entrada.
        String err = validarInput(input);
        if (err != null) {
            throw new ValidationException(err);
        }

        // Obtener persona.
        Result<Persona> resPersona = personas.obtenerPorRuc(input.ruc);
        Persona persona = resPersona.value(null);
        if (persona == null) {
            // Registrar nueva persona.
            if (input.esPersonaFisica) {
                resPersona = personas.registrarPersonaFisica(input.nombres, input.apellidos, input.ci, input.ruc);
                persona = resPersona.value(null);
            } else if (input.esPersonaJuridica) {
                resPersona = personas.registrarPersonaJuridica(input.razonSocial, input.razonSocial, input.ruc);
                persona = resPersona.value(null);
            } else {
                throw Errors.illegalState();
            }
        }

        // Agregar rol de comprador.
        Result<PersonaRol> resRol = personas.agregarRol(persona.getId(), PerfilEnum.COMPRADOR);
        resRol.raise();

        // Control.
        if (persona == null) {
            throw new ValidationException("No se pudo registrar al comprador.");
        }

        // Registrar relacion comercial.
        Result<Void> resRelacion = personas.agregarRelacion(usuarioLogueado.getPersona().getId(), persona.getId());
        resRelacion.raise();

        return null;
    }

    private String validarInput(CompradorAltaMB.Input input) {
        // Validar persona juridica.
        if (input.esPersonaJuridica) {
            // Validar razon social.
            if (Assertions.stringNullOrEmpty(input.razonSocial)) {
                return "El campo razón social no puede ser vacío.";
            }
        }

        // Validar persona fisica.
        if (input.esPersonaFisica) {
            // Validar nombres.
            if (Assertions.stringNullOrEmpty(input.nombres)) {
                return "El campo nombres no puede ser vacío.";
            }

            // Validar apellidos.
            if (Assertions.stringNullOrEmpty(input.apellidos)) {
                return "El campo apellidos no puede ser vacío.";
            }

            // Validar ci.
            if (Assertions.stringNullOrEmpty(input.ci)) {
                return "El campo documento de identidad no puede ser vacío.";
            }
        }

        // Validar ruc.
        if (Assertions.stringNullOrEmpty(input.ruc)) {
            return "El campo RUC no puede ser vacío.";
        }
        if (!Assertions.isRuc(input.ruc)) {
            return "El campo RUC es inválido.";
        }

        return null;
    }

    public void onPersonaFisicaChanged() {
        this.input.esPersonaJuridica = !this.input.esPersonaFisica;
    }

    public void onPersonaJuridicaChanged() {
        this.input.esPersonaFisica = !this.input.esPersonaJuridica;
    }

    private void updateViewAltaFacturaForm() {
        Prime.update("alta_comprador_form");
    }

    @Data
    public static class Input implements Serializable {

        private boolean esPersonaFisica;
        private String nombres;
        private String apellidos;
        private String ci;
        private boolean esPersonaJuridica;
        private String razonSocial;
        private String nombreFantasia;
        private String ruc;

        public Input() {
            this.esPersonaFisica = false;
            this.nombres = "";
            this.apellidos = "";
            this.ci = "";
            this.esPersonaJuridica = true;
            this.razonSocial = "";
            this.ruc = "";
        }
    }

}

genisys-web/src/main/java/py/com/sepsa/genisys/web/controllers/comprador/CompradorMB.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package py.com.sepsa.genisys.web.controllers.comprador;

import fa.gs.utils.misc.text.Strings;
import java.io.Serializable;
import javax.annotation.PostConstruct;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import lombok.Getter;
import lombok.Setter;
import org.omnifaces.util.Ajax;
import py.com.sepsa.genisys.ejb.entities.info.PersonaInfo;
import py.com.sepsa.genisys.ejb.utils.Ids;
import py.com.sepsa.genisys.web.controllers.BasicViewMB;
import py.com.sepsa.genisys.web.utils.CustomFilter;
import py.com.sepsa.genisys.web.utils.Prime;

/**
 *
 * @author Fabio A. González Sosa
 */
@Named(value = "compradores")
@ViewScoped
public class CompradorMB extends BasicViewMB implements Serializable {

    @Inject
    @Getter
    @Setter
    private py.com.sepsa.genisys.web.controllers.comprador.ListaMB lista;

    @PostConstruct
    public void init() {
        ;
    }

    public void initAltaComprador() {
        Prime.redirect("app/abm/comprador/alta.xhtml?redirect-true");
    }

    public void initCambiarPersoneria() {
        PersonaInfo persona = checkSeleccionUnica(lista);
        if (persona != null) {
            String id = Ids.mask(persona.getId());
            String path = Strings.format("app/abm/comprador/cambiar_personeria.xhtml?p=%s", id);
            Prime.redirect(path);
        }
    }

    public void initVerContacto() {
        PersonaInfo persona = checkSeleccionUnica(lista);
        if (persona != null) {
            String id = Ids.mask(persona.getId());
            String path = Strings.format("app/abm/comprador/ver_contacto.xhtml?p=%s", id);
            Prime.redirect(path);
        }
    }

    public void filtrarLista() {
        lista.filter();
        updateViewFiltrosForm();
    }

    public void limpiarFiltroForm() {
        CustomFilter filtro = lista.getFiltro();
        if (!filtro.isEnabled()) {
            filtro.clearFilterValues();
            updateViewFiltrosForm();
        }
    }

    public void recargarListaCompradores() {
        lista.clearSelections();
        updateViewListaDeCompradores();
        lista.reload();
        updateViewListaDeCompradores();
    }

    public String htmlPersoneria(PersonaInfo persona) {
        return persona.getTipoPersona().descripcion();
    }

    private void updateViewFiltrosForm() {
        Ajax.update("filtro_compradores_panel:filtro_compradores_form");
        Prime.showBlockUi("bui", lista.getFiltro().isEnabled());
        updateViewListaDeCompradores();
    }

    private void updateViewListaDeCompradores() {
        lista.clearSelections();
        Ajax.update("tabla_compradores_panel:tabla_compradores_form:tabla_compradores");
        Prime.executeJs("$.fn.matchHeight._update();");
    }

    //<editor-fold defaultstate="collapsed" desc="Getters y Setters">
    public String getBtnFiltrarText() {
        if (lista.getFiltro().isEnabled()) {
            return "Deshacer Filtro";
        } else {
            return "Filtrar Datos";
        }
    }
    //</editor-fold>

}

genisys-web/src/main/java/py/com/sepsa/genisys/web/controllers/comprador/ListaMB.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package py.com.sepsa.genisys.web.controllers.comprador;

import fa.gs.criteria.query.Order;
import fa.gs.misc.Assertions;
import fa.gs.utils.collections.Lists;
import fa.gs.utils.database.query.expressions.literals.SQLStringLiterals;
import fa.gs.utils.misc.text.Strings;
import java.io.Serializable;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.enterprise.context.Dependent;
import lombok.Data;
import py.com.sepsa.genisys.ejb.entities.info.PersonaInfo;
import py.com.sepsa.genisys.ejb.logic.impl.Personas;
import py.com.sepsa.genisys.ejb.utils.Injection;
import py.com.sepsa.genisys.web.utils.CustomFilter;
import py.com.sepsa.genisys.web.utils.CustomLazyDataModel;

/**
 *
 * @author Fabio A. González Sosa
 */
@Dependent
public class ListaMB extends py.com.sepsa.genisys.web.controllers.ListaMB<PersonaInfo> implements Serializable {

    @Override
    protected CustomLazyDataModel<PersonaInfo> buildItemsLoader() {
        if (usuarioLogueado.esAdministrador()) {
            return new CompradoresTodosLazyList();
        } else if (usuarioLogueado.esProveedor()) {
            return new CompradoresDeProveedorLazyList(usuarioLogueado.getPersona().getId());
        } else {
            return new CompradoresDefaultLazyList();
        }
    }

    @Override
    protected CustomFilter buildItemsFilter() {
        return new CompradorListFilter();
    }

    /**
     * Clase que encapsula la carga progresiva de facturas desde la BD.
     */
    private class CompradoresDefaultLazyList extends CustomLazyDataModel<PersonaInfo> {

        /**
         * Constructor.
         */
        public CompradoresDefaultLazyList() {
            super(null);
        }

        /**
         * Realiza una carga lazy de datos desde la BD.
         *
         * @param offset cantidad de registros a omitor.
         * @param limit cantidad máxima de registros a obtener.
         * @param sorts criterios de ordenacion de datos.
         * @param filter criterios de filtrado de datos.
         * @return Lista de entidades recuperadas desde BD.
         */
        @Override
        public List<PersonaInfo> lazyLoad(int offset, int limit, Map<String, Order> sorts, Map<String, Object> filter) {
            return Lists.empty();
        }

    }

    /**
     * Clase que encapsula la carga progresiva de facturas a mostrar a los
     * compradores.
     */
    private class CompradoresTodosLazyList extends CustomLazyDataModel<PersonaInfo> {

        private Personas personas;

        /**
         * Constructor.
         */
        public CompradoresTodosLazyList() {
            super(null);
            this.personas = Injection.lookup(Personas.class);
        }

        /**
         * Realiza una carga lazy de datos desde la BD.
         *
         * @param offset cantidad de registros a omitor.
         * @param limit cantidad máxima de registros a obtener.
         * @param sorts criterios de ordenacion de datos.
         * @param filter criterios de filtrado de datos.
         * @return Lista de entidades recuperadas desde BD.
         */
        @Override
        public List<PersonaInfo> lazyLoad(int offset, int limit, Map<String, Order> sorts, Map<String, Object> filter) {
            // Ordenacion automatica.
            sorts.put("P.razon_social", Order.ASCENDING);
            sorts.put("P.ruc", Order.ASCENDING);

            // Busqueda de registros.
            List<PersonaInfo> data = personas.selectCompradores(null, limit, offset, filter, sorts);
            Integer total = personas.countCompradores(null, filter);
            setRowCount(total);
            return data;
        }

    }

    /**
     * Clase que encapsula la carga progresiva de facturas a mostrar a los
     * compradores.
     */
    private class CompradoresDeProveedorLazyList extends CustomLazyDataModel<PersonaInfo> {

        private Integer idProveedor;

        private Personas personas;

        /**
         * Constructor.
         */
        public CompradoresDeProveedorLazyList(Integer idProveedor) {
            super(null);
            this.idProveedor = idProveedor;
            this.personas = Injection.lookup(Personas.class);
        }

        /**
         * Realiza una carga lazy de datos desde la BD.
         *
         * @param offset cantidad de registros a omitor.
         * @param limit cantidad máxima de registros a obtener.
         * @param sorts criterios de ordenacion de datos.
         * @param filter criterios de filtrado de datos.
         * @return Lista de entidades recuperadas desde BD.
         */
        @Override
        public List<PersonaInfo> lazyLoad(int offset, int limit, Map<String, Order> sorts, Map<String, Object> filter) {
            // Ordenacion automatica.
            sorts.put("P.razon_social", Order.ASCENDING);
            sorts.put("P.ruc", Order.ASCENDING);

            // Busqueda de registros.
            List<PersonaInfo> data = personas.selectCompradores(idProveedor, limit, offset, filter, sorts);
            Integer total = personas.countCompradores(idProveedor, filter);
            setRowCount(total);
            return data;
        }

    }

    /**
     * Clase que encapsula los campos y operadores de filtro aplicables a la
     * lista principal de facturas.
     */
    @Data
    public class CompradorListFilter extends CustomFilter {

        private String razonSocial;
        private String ruc;

        @Override
        final public void clearFilterValues() {
            this.razonSocial = "";
            this.ruc = "";
        }

        @Override
        public Map<String, Object> getFilters() {
            Map<String, Object> filters = new HashMap<>();

            // Filtro de razon social.
            if (!Assertions.stringNullOrEmpty(razonSocial)) {
                filters.put("razonSocial", Strings.format(" P.razon_social ilike '%s' ", SQLStringLiterals.likefy(razonSocial)));
            }

            // Filtro de ruc.
            if (!Assertions.stringNullOrEmpty(ruc)) {
                filters.put("ruc", Strings.format(" P.ruc ilike '%s' ", SQLStringLiterals.likefy(ruc)));
            }

            return filters;
        }

    }
}

genisys-web/src/main/webapp/app/abm/comprador/fragments/comprador_nuevo.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:sec="http://www.springframework.org/security/tags"
    xmlns:p="http://primefaces.org/ui"
    xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
    xmlns:sepsa="http://java.sun.com/jsf/composite/components"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets">

    <h:form id="alta_comprador_form">
        <!-- DATOS DE COMPRADOR -->
        <div class="form-group row">
            <div class="col-md-12">
                <div class="h3">Datos de Comprador</div>
                <hr/>
            </div>
        </div>

        <div class="form-group row">
            <label class="form-control-label col-md-2">Personería</label>
            <div class="col-md-4">
                <ul>
                    <li>
                        <p:selectBooleanCheckbox itemLabel="Persona Física" value="#{altaComprador.input.esPersonaFisica}">
                            <p:ajax update="@form" process="@form" listener="#{altaComprador.onPersonaFisicaChanged}" />
                        </p:selectBooleanCheckbox>
                    </li>
                    <li>
                        <p:selectBooleanCheckbox itemLabel="Persona Jurídica" value="#{altaComprador.input.esPersonaJuridica}">
                            <p:ajax update="@form" process="@form" listener="#{altaComprador.onPersonaJuridicaChanged}" />
                        </p:selectBooleanCheckbox>
                    </li>
                </ul>
            </div>
        </div>

        <h:panelGroup layout="block" class="form-group row" rendered="#{altaComprador.input.esPersonaFisica eq true}">
            <label class="form-control-label col-md-2">Nombres</label>
            <div class="col-md-4">
                <p:inputText value="#{altaComprador.input.nombres}" class="app_form_input" />
            </div>
        </h:panelGroup>

        <h:panelGroup layout="block" class="form-group row" rendered="#{altaComprador.input.esPersonaFisica eq true}">
            <label class="form-control-label col-md-2">Apellidos</label>
            <div class="col-md-4">
                <p:inputText value="#{altaComprador.input.apellidos}" class="app_form_input" />
            </div>
        </h:panelGroup>

        <h:panelGroup layout="block" class="form-group row" rendered="#{altaComprador.input.esPersonaFisica eq true}">
            <label class="form-control-label col-md-2">Documento de Identidad</label>
            <div class="col-md-4">
                <p:inputText value="#{altaComprador.input.ci}" class="app_form_input" />
            </div>
        </h:panelGroup>

        <h:panelGroup layout="block" class="form-group row" rendered="#{altaComprador.input.esPersonaJuridica eq true}">
            <label class="form-control-label col-md-2">Razón Social</label>
            <div class="col-md-4">
                <p:inputText value="#{altaComprador.input.razonSocial}" class="app_form_input" />
            </div>
        </h:panelGroup>

        <h:panelGroup layout="block" class="form-group row" rendered="#{altaComprador.input.esPersonaJuridica eq true}">
            <label class="form-control-label col-md-2">Nombre de Fantasía</label>
            <div class="col-md-4">
                <p:inputText value="#{altaComprador.input.nombreFantasia}" class="app_form_input" />
            </div>
        </h:panelGroup>

        <div class="form-group row">
            <div class="col-md-2">
                <div class="form-control-label">RUC</div>
                <span class="form-text text-muted">Incluir dígito verificador</span>
            </div>
            <div class="col-md-4">
                <p:inputText value="#{altaComprador.input.ruc}" class="app_form_input" placeholder="XXXXXXX-X"/>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-md-12">
                <p:commandButton value="Guardar" action="#{altaComprador.guardar}" process="@form" update="@form" />
            </div>
        </div>

        <div class="form-group row">
            <div class="col-md-12">
                <sepsa:messages />
            </div>
        </div>
    </h:form>

</ui:composition>

genisys-web/src/main/webapp/app/abm/comprador/fragments/tabla_compradores.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:sec="http://www.springframework.org/security/tags"
    xmlns:p="http://primefaces.org/ui"
    xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
    xmlns:sepsa="http://java.sun.com/jsf/composite/components"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets">

    <h:form id="tabla_compradores_form">
        <input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}"/>
        <p:dataTable
            id="tabla_compradores"
            binding="#{compradores.lista.tableBind}"
            var="comprador"
            value="#{compradores.lista.items}"
            lazy="true"
            emptyMessage="No existen datos que mostrar"
            paginator="true"
            currentPageReportTemplate="Mostrando {startRecord} a {endRecord} de {totalRecords}"
            paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown} {SelectedCount}"
            paginatorAlwaysVisible="true"
            paginatorPosition="top"
            selection="#{compradores.lista.multiSelectedItem}"
            rows="50"
            rowsPerPageTemplate="10,15,20,30,50,100"
            rowKey="#{comprador.id}"
            reflow="true"
            resizableColumns="true"
            >

            <!-- Elemento que indica la cantidad de filas seleccionadas -->
            <f:facet name="{SelectedCount}">
                <h:outputText class="ui-paginator-current" value=" (#{compradores.lista.multiSelectedItem.size()} elementos seleccionados)" rendered="#{compradores.lista.multiSelectedItem.size() > 0}"/>
            </f:facet>

            <!-- Eventos que actualizan las filas seleccionads -->
            <p:ajax event="toggleSelect" update="@parent" />
            <p:ajax event="rowSelect" update="@parent" />
            <p:ajax event="rowUnselect" update="@parent" />
            <p:ajax event="rowSelectCheckbox" update="@parent" />
            <p:ajax event="rowUnselectCheckbox" update="@parent" />
            <p:ajax event="page" oncomplete="$.fn.matchHeight._update();" />

            <p:column selectionMode="multiple" class="app_cbx_selection" style="margin: 0; width: 50px;">
            </p:column>

            <sec:authorize access="hasRole('ROLE_ADMINISTRADOR')" >
                <p:column headerText="ID">
                    <h:outputText value="#{comprador.id}" id="persona_id"/>
                    <p:tooltip for="persona_id" value="#{comprador.id}" />
                </p:column>
            </sec:authorize>

            <p:column headerText="Razón Social">
                <h:outputText value="#{comprador.razonSocial}" id="razon_social"/>
                <p:tooltip for="razon_social" value="#{comprador.razonSocial}" />
            </p:column>

            <p:column headerText="Personería">
                <h:outputText value="#{compradores.htmlPersoneria(comprador)}" id="pesoneria"/>
                <p:tooltip for="pesoneria" value="#{compradores.htmlPersoneria(comprador)}" />
            </p:column>

            <p:column headerText="RUC">
                <h:outputText value="#{comprador.ruc}" id="ruc"/>
                <p:tooltip for="ruc" value="#{comprador.ruc}" />
            </p:column>

        </p:dataTable>
    </h:form>

</ui:composition>

genisys-web/src/main/webapp/app/abm/comprador/fragments/tabla_filtros.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:sec="http://www.springframework.org/security/tags"
    xmlns:p="http://primefaces.org/ui"
    xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
    xmlns:sepsa="http://java.sun.com/jsf/composite/components"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets">

    <h:form id="filtro_compradores_form" class="form-horizontal" role="form">
        <input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}"/>

        <!-- Valores de Filtro -->
        <p:outputPanel id="filtro_compradores_inner">
            <div class="row auto-clear">
                <div class="col-xs-6 col-sm-6 col-md-4 col-lg-3 app_padded_10">
                    <p:outputLabel class="col-md-3 control-label">Razón Social</p:outputLabel>
                    <div class="col-md-9">
                        <p:inputText value="#{compradores.lista.filtro.razonSocial}" class="app_form_input" />
                    </div>
                </div>

                <div class="col-xs-6 col-sm-6 col-md-4 col-lg-3 app_padded_10">
                    <p:outputLabel class="col-md-3 control-label">RUC</p:outputLabel>
                    <div class="col-md-9">
                        <p:inputText value="#{compradores.lista.filtro.ruc}" class="app_form_input" />
                    </div>
                </div>
            </div>
        </p:outputPanel>

        <div class="row">
            <div class="col-xs-6 col-sm-6 col-md-4 col-lg-3 app_padded_10">
                <div class="col-md-12" style="margin-top: 10px;">
                    <p:commandButton value="#{compradores.btnFiltrarText}" action="#{compradores.filtrarLista}"/>
                    &#160;&#160;
                    <p:commandButton value="Limpiar" action="#{compradores.limpiarFiltroForm}"/>
                </div>
            </div>
        </div>

        <!-- Bloquea el panel de valores de filtro para no permitir la edicion de los mismos -->
        <p:blockUI block="filtro_compradores_inner" widgetVar="bui"/>
    </h:form>

</ui:composition>